### PR TITLE
Namespaces as a solution for performance measurements in shared clusters.

### PR DESCRIPTION
**Pull request by BrunoScaglione**

### CODE REVIEW

**Comment by stas00** [comment]
Thank you for the suggestion, Bruno. But this is specific to Kubernetes. I'm talking about a typical SLURM training cluster which has no such functionality. I have no experience with Kubernetes to discuss it, as I always work with SLURM.

I probably should clarify in that text that I'm talking about SLURM, should I?

**Comment by BrunoScaglione** [comment]
Oh sorry, I didn't realize it was specific to SLURM. Also, I thought other orchestrators would have similar functionality, but as it turns out, not quite.

Yes, I think the clarification would help!

**Comment by stas00** [comment]
super, done!

**Comment by stas00** [comment]
thank you for helping to make the text more clear and suggesting that kubernetes has a solution around it, Bruno!

**Pull request merged**
