### PR TITLE
Gaudi 3 MAMF WIP

### PR DESCRIPTION
**Pull request by flozi00**

### CODE REVIEW

**Comment by flozi00** [comment]
[Iteration1.txt](https://github.com/user-attachments/files/18162748/Iteration1.txt)

**Comment by stas00** [comment]
thank you very much for running this on Gaudi3, @flozi00!

I'm aware that you haven't marked this PR as ready for review - if it helps, given that Gaudi2's best MAMF shape was 20224x11520x19968 - you probably need to increase the max values to at least around 21k - you can skip the first 15k and perhaps using a larger step to identify the promising range and once narrowed down finetuning the step to a lower value.

**Comment by flozi00** [comment]
Yeah i did this, but for now its running without a better score.
I will check tomorrow and friday again.
Will mark as ready to review when the final results are available.

**Comment by stas00** [comment]
Perhaps some inefficiencies in their software stack for the new hw? This is dramatically worse than Gaudi2's results of the same.

If you're paying for it I'd ask the support to why this is so. Perhaps you need to enable some flags/env vars to get the full power.

**Comment by flozi00** [comment]
We were not able to get higher scores, even with different Env var configs

**Comment by stas00** [comment]
Thank you for investing time in experimenting, Florian. Probably the software needs to catch up.

Let's merge it then as it is and then hopefully Intel will improve it later.

**Pull request merged**
