### PR TITLE
[feat] md2pdf

### LINKED ISSUE #6: convert markdown to pdf
Hi, I had a good read of this book! Wondering if we can convert the markdown files to PDF so that we can print it out to read. I would like to submit a pr for that! Let me know if you are interested!

### PR DESCRIPTION
**Pull request by pengzhangzhi**
The script generates the pdf files at the same dir of the corresponding md file and concatenates them into one final pdf.
Here is the generated final pdf file.
[book.pdf](https://github.com/stas00/ml-engineering/files/13073678/book.pdf)
resolve #6 
cc @amorehead @stas00

### CODE REVIEW

**Comment by amorehead** [comment]
LGTM. The only thing that stands out to me is that the SLURM script header examples seem to have very large fonts compared to the rest of the document.

**Comment by stas00** [comment]
how is the progress on figuring out the markdown to html issue, @pengzhangzhi?

If it doesn't go well, surely there are other converters, no?

**Comment by pengzhangzhi** [comment]
Hi, sorry for the late response. I have been involved in other works. Now, I use another framework to generate the intermediate HTML files from the markdown files. The book.pdf is attached. LMK if there are further issues!
[book.pdf](https://github.com/stas00/ml-engineering/files/13328493/book.pdf)

**Comment by stas00** [comment]
this pipeline now handles `#SBATCH` correctly, thank you.

For some reason it doesn't handle links though, e.g. see:

snapshot_465

**Comment by stas00** [comment]
OK, the next thing to figure out is the overflow of code sections - a lot of the code examples are chopped off by the pdf. It's not that very wide, perhaps we should scale the text size by some 30-40%? I don't see where we can control the font size for all of the text or just for code.

I think probably the first thing to try is just a consistently smaller font size?

**Comment by stas00** [comment]
Then the internal links don't work in the PDF, e.g. if you click on anything in the TOC page of the PDF it tries to open a browser with a relative link, not take you to the right page in the pdf.

I don't know if it helps in the past I found `wkhtmltopdf` to be excellent at making functional multi-chapter pdfs and whose output can be controlled via many flags (e.g. zooming, font-size, automatic-TOC generation, etc.)

**Comment by stas00** [comment]
oddly it doesn't turn normal http links into clickable links as it http://google.com/, whereas pretty much any md rendering software does it automatically

**Comment by amorehead** [comment]
I just noticed that @pengzhangzhi's original book.pdf corrected word-wraps code snippets (even though it formats them oddly), whereas the latest book.pdf correctly formats code snippet blocks but does not word-wrap them. Very strange.

**Comment by stas00** [comment]
@pengzhangzhi, I have pushed 3 additions:

1. added a header page
2. added a file `chapters.txt` to control chapter order
3. added a cleanup at the end

the above problems list is still the same

**Comment by stas00** [comment]
One more thing to consider - what to do with all the non-md files - .py, .slurm, etc., it'd be difficult to read the pdf if these are missing, as they are part of the book.

**Comment by stas00** [comment]
As this PR looked abandoned and not addressing the problems I built a different process with md -> html -> pdf which works really well.

The building workflow is ready, but I need to finish the stylesheets and restructuring the chapters.

If you're impatient, the instructions are here https://github.com/stas00/ml-engineering/tree/master/build - but as I said the stylesheet needs a bit more work.

So closing this one for now.

Thank you, @pengzhangzhi for the initial attempt!

**Comment by pengzhangzhi** [comment]
Thank you @stas00 for the awesome work!

**Pull request closed without merging**
